# Generated by Django 2.2 on 2019-04-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day1',
        ),
    ]
