# Generated by Django 2.2 on 2019-04-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day1', '0004_auto_20190415_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day11',
            name='id',
        ),
        migrations.RemoveField(
            model_name='day12',
            name='id',
        ),
        migrations.RemoveField(
            model_name='day13',
            name='id',
        ),
        migrations.AlterField(
            model_name='day11',
            name='ans1_1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='day11',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='day12',
            name='ans1_2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='day12',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='day13',
            name='ans1_3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='day13',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
