# Generated by Django 2.2 on 2019-04-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day1', '0005_auto_20190415_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day11',
            name='time',
        ),
    ]
