# Generated by Django 2.2 on 2019-04-15 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day1', '0008_auto_20190415_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day11',
            old_name='ans1_1',
            new_name='ans',
        ),
        migrations.AlterField(
            model_name='day11',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
