# Generated by Django 2.2 on 2019-04-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day1', '0010_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day11',
            name='user',
        ),
        migrations.RemoveField(
            model_name='day12',
            name='user',
        ),
        migrations.RemoveField(
            model_name='day13',
            name='user',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Day11',
        ),
        migrations.DeleteModel(
            name='Day12',
        ),
        migrations.DeleteModel(
            name='Day13',
        ),
    ]
